version: '3'

services:
    mongo:
        container_name: openhim-mongo
        image: mongo:3.4
        ports:
            - "27017:27017"
        volumes:
            - ./openhim_db.gz:/openhim_db.gz
            - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh

    core:
        container_name: openhim-core
        build:
          context: .
          dockerfile: Dockerfile
        environment:
            - mongo_url=mongodb://mongo/openhim
            - mongo_atnaUrl=mongodb://mongo/openhim
        ports:
            - "8080:8080"
            - "5000:5000"
            - "5001:5001"
            - "5050:5050"
            - "5051:5051"
            - "5052:5052"
            - "7788:7788"
        depends_on:
            - mongo

    console:
        container_name: openhim-console
        image: jembi/openhim-console
        ports:
            - "80:80"
        volumes:
            - ./default.json:/usr/share/nginx/html/config/default.json
        depends_on:
            - core